title: Fallout 4 Modding Documentation Hub
description: A hub for Fallout 4 modding resources, tools, and guides.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

nav:
  - title: Home
    url: /
  - title: Getting Started
    url: /docs/getting-started
  - title: Modding Tools
    url: /docs/modding-tools
  - title: Scripting
    url: /docs/scripting
  - title: FAQ
    url: /docs/faq
  - title: Test Page
    url: /test-page
